/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateLayoutRouteImport } from './routes/_private/layout'
import { Route as PrivatePageRouteImport } from './routes/_private/page'
import { Route as publicGuestLayoutRouteImport } from './routes/(public)/_guest/layout'
import { Route as publicGuestSignupPageRouteImport } from './routes/(public)/_guest/signup/page'
import { Route as publicGuestLoginPageRouteImport } from './routes/(public)/_guest/login/page'

const publicRouteImport = createFileRoute('/(public)')()

const publicRoute = publicRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLayoutRoute = PrivateLayoutRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatePageRoute = PrivatePageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const publicGuestLayoutRoute = publicGuestLayoutRouteImport.update({
  id: '/_guest',
  getParentRoute: () => publicRoute,
} as any)
const publicGuestSignupPageRoute = publicGuestSignupPageRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => publicGuestLayoutRoute,
} as any)
const publicGuestLoginPageRoute = publicGuestLoginPageRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => publicGuestLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivatePageRoute
  '/login': typeof publicGuestLoginPageRoute
  '/signup': typeof publicGuestSignupPageRoute
}
export interface FileRoutesByTo {
  '/': typeof PrivatePageRoute
  '/login': typeof publicGuestLoginPageRoute
  '/signup': typeof publicGuestSignupPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateLayoutRouteWithChildren
  '/(public)': typeof publicRouteWithChildren
  '/(public)/_guest': typeof publicGuestLayoutRouteWithChildren
  '/_private/': typeof PrivatePageRoute
  '/(public)/_guest/login/': typeof publicGuestLoginPageRoute
  '/(public)/_guest/signup/': typeof publicGuestSignupPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup'
  id:
    | '__root__'
    | '/_private'
    | '/(public)'
    | '/(public)/_guest'
    | '/_private/'
    | '/(public)/_guest/login/'
    | '/(public)/_guest/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateLayoutRoute: typeof PrivateLayoutRouteWithChildren
  publicRoute: typeof publicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivatePageRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/(public)/_guest': {
      id: '/(public)/_guest'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicGuestLayoutRouteImport
      parentRoute: typeof publicRoute
    }
    '/(public)/_guest/signup/': {
      id: '/(public)/_guest/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof publicGuestSignupPageRouteImport
      parentRoute: typeof publicGuestLayoutRoute
    }
    '/(public)/_guest/login/': {
      id: '/(public)/_guest/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicGuestLoginPageRouteImport
      parentRoute: typeof publicGuestLayoutRoute
    }
  }
}

interface PrivateLayoutRouteChildren {
  PrivatePageRoute: typeof PrivatePageRoute
}

const PrivateLayoutRouteChildren: PrivateLayoutRouteChildren = {
  PrivatePageRoute: PrivatePageRoute,
}

const PrivateLayoutRouteWithChildren = PrivateLayoutRoute._addFileChildren(
  PrivateLayoutRouteChildren,
)

interface publicGuestLayoutRouteChildren {
  publicGuestLoginPageRoute: typeof publicGuestLoginPageRoute
  publicGuestSignupPageRoute: typeof publicGuestSignupPageRoute
}

const publicGuestLayoutRouteChildren: publicGuestLayoutRouteChildren = {
  publicGuestLoginPageRoute: publicGuestLoginPageRoute,
  publicGuestSignupPageRoute: publicGuestSignupPageRoute,
}

const publicGuestLayoutRouteWithChildren =
  publicGuestLayoutRoute._addFileChildren(publicGuestLayoutRouteChildren)

interface publicRouteChildren {
  publicGuestLayoutRoute: typeof publicGuestLayoutRouteWithChildren
}

const publicRouteChildren: publicRouteChildren = {
  publicGuestLayoutRoute: publicGuestLayoutRouteWithChildren,
}

const publicRouteWithChildren =
  publicRoute._addFileChildren(publicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PrivateLayoutRoute: PrivateLayoutRouteWithChildren,
  publicRoute: publicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
